<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import type { ProjectItem } from '../../composables/useTaskSync';
import type { Provider } from './RunWorkspace.vue';
const props = defineProps<{ mode: 'requirement' | 'docs' | null; projects: ProjectItem[]; provider: Provider; busy: boolean; requirementPlan: string; docsReady: boolean; message: string; output: string; phase: string; error: string }>();
const emit = defineEmits<{ close: []; runRequirement: [data: { projectId: number; requirement: string }]; reviseRequirement: [data: { projectId: number; requirement: string; feedback: string }]; updateProposal: [proposal: string]; createBacklog: []; runDocs: [projectId: number]; saveDocs: []; syncDocs: [] }>();
const projectId = ref<number | null>(null); const requirement = ref(''); const revisionFeedback = ref(''); const editingProposal = ref(false); const editableProposal = ref('');
watch(() => props.mode, () => { if (!projectId.value && props.projects[0]) projectId.value = props.projects[0].id; });
watch(() => props.requirementPlan, value => { if (!editingProposal.value) editableProposal.value = value; }, { immediate: true });
const canRun = computed(() => Boolean(projectId.value && (props.mode === 'docs' || requirement.value.trim()) && !props.busy));
const liveLines = computed(() => props.output.split(/\r?\n/).filter(Boolean).slice(-10));
const isRequirement = computed(() => props.mode === 'requirement');
const title = computed(() => isRequirement.value ? 'New backlog from requirement' : 'Scan repository documentation');
const subtitle = computed(() => isRequirement.value ? 'Draft work items with AI, then review before anything is created.' : 'Generate a documentation set in an isolated worktree, then review it here.');
</script>
<template>
  <div v-if="mode" class="fixed inset-0 z-[80] flex justify-end bg-black/55 backdrop-blur-[1px]" @click.self="emit('close')">
    <aside class="flex h-full w-full max-w-[680px] flex-col border-l border-[#2a3546] bg-[#0b1019] text-[#e6edf7] shadow-2xl">
      <header class="flex items-start justify-between gap-4 border-b border-[#263244] px-6 py-5"><div><p class="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#7db0ff]">AI workflow</p><h2 class="mt-1 text-lg font-semibold text-white">{{ title }}</h2><p class="mt-1 max-w-xl text-sm leading-6 text-[#a8b5c7]">{{ subtitle }}</p></div><button class="cc-button" @click="emit('close')">Close</button></header>
      <div class="grid grid-cols-3 gap-2 border-b border-[#263244] px-6 py-4"><div class="flex items-center gap-2 text-xs"><span class="grid h-6 w-6 place-items-center rounded-full bg-[#3976e8] font-bold text-white">1</span><span><b class="block text-[#e6edf7]">Brief</b><span class="text-[#8b9bb0]">Scope work</span></span></div><div class="flex items-center gap-2 text-xs"><span class="grid h-6 w-6 place-items-center rounded-full" :class="busy ? 'bg-[#3976e8] text-white' : 'bg-[#202c3c] text-[#a8b5c7]'">2</span><span><b class="block text-[#e6edf7]">Run</b><span class="text-[#8b9bb0]">Local agent</span></span></div><div class="flex items-center gap-2 text-xs"><span class="grid h-6 w-6 place-items-center rounded-full" :class="requirementPlan || docsReady ? 'bg-[#16845b] text-white' : 'bg-[#202c3c] text-[#a8b5c7]'">3</span><span><b class="block text-[#e6edf7]">Review</b><span class="text-[#8b9bb0]">Approve result</span></span></div></div>
      <div class="min-h-0 flex-1 overflow-y-auto px-6 py-5"><div class="space-y-5"><label class="block text-sm font-medium text-[#e6edf7]">Hub project<select v-model="projectId" class="cc-select mt-2"><option :value="null" disabled>Select Hub project</option><option v-for="project in projects" :key="project.id" :value="project.id">{{ project.title }}</option></select></label><label v-if="isRequirement" class="block text-sm font-medium text-[#e6edf7]">Requirement<textarea v-model="requirement" class="cc-input mt-2 min-h-36 resize-y" placeholder="Describe the user need, expected outcome, constraints and acceptance criteria."></textarea><span class="mt-2 block text-xs font-normal leading-5 text-[#8b9bb0]">AI will propose an Epic, Stories and implementation tasks. Nothing is created or synced until you explicitly approve the reviewed draft.</span></label><div class="flex flex-wrap items-center gap-3"><button class="cc-primary" :disabled="!canRun" @click="isRequirement ? emit('runRequirement', { projectId: projectId!, requirement }) : emit('runDocs', projectId!)">{{ busy ? 'AI is working…' : isRequirement ? 'Analyze requirement' : 'Scan & generate docs' }}</button><span v-if="message" class="text-sm text-[#a8b5c7]">{{ message }}</span></div><p v-if="error" class="rounded-lg border border-[#71333c] bg-[#28171c] px-3 py-2 text-sm text-[#fca5a5]">{{ error }}</p>
        <section v-if="busy || liveLines.length" class="overflow-hidden rounded-lg border border-[#263244] bg-[#070c14]"><div class="flex items-center justify-between border-b border-[#1c293a] px-4 py-2 text-xs"><span class="font-medium text-[#cbd5e1]">Live agent activity</span><span class="text-[#7db0ff]">{{ phase }}</span></div><pre class="max-h-44 overflow-auto whitespace-pre-wrap px-4 py-3 font-mono text-xs leading-5 text-[#cbd5e1]">{{ liveLines.join('\n') || 'Preparing isolated workspace…' }}</pre></section>
        <section v-if="isRequirement && requirementPlan" class="overflow-hidden rounded-xl border border-[#315887] bg-[#101b2a]"><header class="flex items-center justify-between gap-4 border-b border-[#315887] px-4 py-3"><div><p class="text-sm font-semibold text-white">Backlog proposal ready</p><p class="mt-1 text-xs text-[#a8b5c7]">Nothing is synced yet. Review, edit or request changes, then explicitly approve creation.</p></div><div class="flex shrink-0 gap-2"><button class="cc-button" :disabled="busy" @click="editingProposal = !editingProposal; editableProposal = requirementPlan">{{ editingProposal ? 'Cancel edit' : 'Edit draft' }}</button><button class="cc-primary" :disabled="busy || editingProposal" @click="emit('createBacklog')">Approve & create backlog</button></div></header><textarea v-if="editingProposal" v-model="editableProposal" class="cc-input m-4 min-h-80 w-[calc(100%-2rem)] resize-y font-mono text-xs leading-5" aria-label="Edit backlog proposal"></textarea><pre v-else class="max-h-80 overflow-auto whitespace-pre-wrap p-4 font-mono text-xs leading-5 text-[#dbe5f1]">{{ requirementPlan }}</pre><div v-if="editingProposal" class="flex items-center gap-3 border-t border-[#315887] px-4 py-3"><button class="cc-primary" :disabled="busy || !editableProposal.trim()" @click="emit('updateProposal', editableProposal.trim()); editingProposal = false">Save draft</button><span class="text-xs text-[#8b9bb0]">The draft is validated when you approve it; malformed plans are never synced.</span></div><div class="border-t border-[#315887] p-4"><label class="block text-xs font-medium text-[#dbe5f1]">Request changes from AI<textarea v-model="revisionFeedback" class="cc-input mt-2 min-h-24 resize-y" placeholder="Example: split Story 2, add a migration task and make acceptance criteria measurable."></textarea></label><div class="mt-3 flex items-center gap-3"><button class="cc-button" :disabled="busy || !revisionFeedback.trim()" @click="emit('reviseRequirement', { projectId: projectId!, requirement, feedback: revisionFeedback }); revisionFeedback = ''">Request revision</button><span class="text-xs text-[#8b9bb0]">The revised proposal replaces this draft; it still will not sync until approval.</span></div></div></section>
        <section v-if="!isRequirement && docsReady" class="rounded-xl border border-[#287052] bg-[#10271f] p-4"><p class="font-semibold text-[#d1fae5]">Documentation ready for review</p><p class="mt-1 text-sm leading-6 text-[#a7f3d0]">Save the reviewed documents to the repository or sync them to Task Hub.</p><div class="mt-4 flex flex-wrap gap-2"><button class="cc-button" @click="emit('saveDocs')">Save to repository</button><button class="cc-primary" @click="emit('syncDocs')">Sync docs to Hub</button></div></section>
      </div></div>
      <footer class="border-t border-[#263244] px-6 py-3 text-xs text-[#8b9bb0]">Runs locally in an isolated worktree. No repository changes are applied until you choose an action.</footer>
    </aside>
  </div>
</template>
