import type { TaskItem, ProjectItem } from './useTaskSync';

export const DEFAULT_ROADMAP_PROJECTS: ProjectItem[] = [
  {
    id: 1,
    title: 'Task Hub Roadmap & Evolution',
    slug: 'task-hub-roadmap-evolution',
    key: 'THUB',
    color: '#00f5a0',
  },
  {
    id: 2,
    title: 'Mindfulness Desktop Tools',
    slug: 'mindfulness-desktop-tools',
    key: 'MIND',
    color: '#8b5cf6',
  },
];

export function getDefaultRoadmapTasks(): TaskItem[] {
  const now = new Date();
  const getLocalDateString = (d: Date) => {
    const year = d.getFullYear();
    const month = String(d.getMonth() + 1).padStart(2, '0');
    const day = String(d.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  };

  const todayStr = getLocalDateString(now);
  const tomorrow = new Date(now.getTime() + 86400000);
  const tomorrowStr = getLocalDateString(tomorrow);
  const nextWeek = new Date(now.getTime() + 7 * 86400000);
  const nextWeekStr = getLocalDateString(nextWeek);

  return [
    // --- EPIC 1: Quick Capture & Smart Task Entry (P0) ---
    {
      id: 101,
      project_id: 1,
      issue_key: 'THUB-01',
      title: 'Global Quick-Add Overlay Bar (Thanh nhập việc nhanh toàn cục)',
      description: 'Nhấn tổ hợp phím tắt toàn cục Ctrl + Alt + Space từ bất kỳ cửa sổ nào trên Windows để mở ngay một thanh input nổi thanh mảnh giữa màn hình, cho phép gõ việc và bấm Enter lưu ngay vào danh sách.',
      status: 'in_progress',
      priority: 'urgent',
      category: 'desktop',
      estimated_pomodoros: 2,
      completed_pomodoros: 1,
      due_date: todayStr,
      completed_at: null,
      notes: '- [x] Đăng ký phím tắt toàn cục Ctrl+Alt+Space trong Electron main process\n- [ ] Thiết kế cửa sổ frameless bán trong suốt căn giữa màn hình\n- [ ] Xử lý phím Enter lưu việc tức thì và tự động ẩn\n- [ ] Hỗ trợ phím Esc để hủy nhanh mà không lưu',
    },
    {
      id: 102,
      project_id: 1,
      issue_key: 'THUB-02',
      title: 'Vietnamese Natural Language Date Parsing (Bóc tách ngày giờ tự nhiên tiếng Việt)',
      description: 'Tự động nhận diện và trích xuất ngày giờ từ câu văn gõ tiếng Việt tự nhiên (VD: "họp phòng ban chiều mai 3h", "nộp báo cáo thứ 6 tuần sau").',
      status: 'todo',
      priority: 'high',
      category: 'desktop',
      estimated_pomodoros: 3,
      completed_pomodoros: 0,
      due_date: todayStr,
      completed_at: null,
      notes: '- [ ] Nhận diện chính xác "hôm nay", "ngày mai", "thứ X tuần sau"\n- [ ] Bóc tách giờ cụ thể (VD: 3h chiều -> 15:00)\n- [ ] Tự động gán due_date chính xác theo múi giờ địa phương',
    },
    {
      id: 103,
      project_id: 1,
      issue_key: 'THUB-03',
      title: 'Voice-to-Task Quick Dictation (Nhập việc bằng giọng nói tiếng Việt)',
      description: 'Nút micro thu âm nhanh trên thanh Quick Add sử dụng Web Speech API hoặc mô hình Whisper cục bộ, chuyển lời nói thành tiêu đề và tự động phân tách checklist bước con.',
      status: 'todo',
      priority: 'medium',
      category: 'desktop',
      estimated_pomodoros: 3,
      completed_pomodoros: 0,
      due_date: nextWeekStr,
      completed_at: null,
      notes: '- [ ] Thu âm và nhận diện tiếng Việt chính xác > 90%\n- [ ] Tự động ngắt đoạn thành các bước con khi nói từ khóa "bước tiếp theo"\n- [ ] Có hiệu ứng sóng âm hoạt họa khi thu âm',
    },
    {
      id: 104,
      project_id: 1,
      issue_key: 'THUB-04',
      title: 'Drag-and-Drop Reordering (Kéo thả sắp xếp thứ tự công việc & bước con)',
      description: 'Hỗ trợ kéo thả trực quan các thẻ công việc trong danh sách và các dòng bước con trong drawer chi tiết để sắp xếp thứ tự ưu tiên bằng thao tác chuột tự nhiên.',
      status: 'todo',
      priority: 'medium',
      category: 'desktop',
      estimated_pomodoros: 2,
      completed_pomodoros: 0,
      due_date: tomorrowStr,
      completed_at: null,
      notes: '- [ ] Kéo thả mượt mà với hiệu ứng bóng mờ chỉ vị trí thả\n- [ ] Cập nhật trường sort_order và lưu cache tức thì\n- [ ] Đồng bộ thứ tự mới lên server',
    },

    // --- EPIC 2: Daily Focus, Reminders & Habit Loops (P1) ---
    {
      id: 105,
      project_id: 1,
      issue_key: 'THUB-05',
      title: 'Native Windows Toast Reminders & Daily Briefing (Nhắc việc Windows & Tóm tắt ngày)',
      description: 'Gửi thông báo Windows toast bản địa khi công việc sắp đến hạn hoặc quá hạn. Tích hợp popup Daily Briefing xuất hiện lúc 9:00 sáng tóm tắt 3 công việc quan trọng nhất.',
      status: 'in_progress',
      priority: 'urgent',
      category: 'desktop',
      estimated_pomodoros: 3,
      completed_pomodoros: 1,
      due_date: todayStr,
      completed_at: null,
      notes: '- [x] Bắn thông báo native toast chuẩn Windows 10/11 qua IPC\n- [ ] Click vào thông báo mở thẳng drawer công việc\n- [ ] Cho phép tùy chỉnh bật/tắt và chọn giờ nhận Daily Briefing',
    },
    {
      id: 106,
      project_id: 1,
      issue_key: 'THUB-06',
      title: 'Focus Soundscapes & Pomodoro Companion (Đồng hồ Pomodoro & Âm thanh thư giãn)',
      description: 'Bộ đếm thời gian tập trung Pomodoro chuẩn 25 phút làm việc / 5 phút nghỉ ngơi, tích hợp 4 bộ âm thanh nền tĩnh tâm (tiếng mưa rơi, quán cà phê lofi, sóng biển) kèm mascot.',
      status: 'todo',
      priority: 'medium',
      category: 'desktop',
      estimated_pomodoros: 2,
      completed_pomodoros: 0,
      due_date: tomorrowStr,
      completed_at: null,
      notes: '- [ ] Bộ đếm ngược có chuông báo hết giờ\n- [ ] Tích hợp trình phát âm thanh vòng lặp không gián đoạn\n- [ ] Thống kê số chu kỳ Pomodoro hoàn thành trong ngày',
    },
    {
      id: 107,
      project_id: 1,
      issue_key: 'THUB-07',
      title: 'Recurring Tasks Engine (Hệ thống công việc lặp lại định kỳ)',
      description: 'Hỗ trợ tạo công việc lặp lại theo chu kỳ: hàng ngày, các ngày trong tuần (T2-T6), hàng tuần vào ngày cụ thể, hoặc hàng tháng.',
      status: 'todo',
      priority: 'high',
      category: 'desktop',
      estimated_pomodoros: 3,
      completed_pomodoros: 0,
      due_date: nextWeekStr,
      completed_at: null,
      notes: '- [ ] Chọn chu kỳ lặp lại trong drawer chi tiết\n- [ ] Khi tick hoàn thành task, task mới xuất hiện với due_date kế tiếp\n- [ ] Không làm mất lịch sử các task đã hoàn thành trước đó',
    },
    {
      id: 108,
      project_id: 1,
      issue_key: 'THUB-08',
      title: '2-Way Calendar Sync (Đồng bộ lịch 2 chiều Google Calendar & .ics)',
      description: 'Cung cấp URL lịch iCal cá nhân để nhúng vào Apple Calendar/Outlook và tích hợp Google Calendar API 2 chiều để tự động phản ánh thay đổi hạn chót qua lại.',
      status: 'todo',
      priority: 'low',
      category: 'desktop',
      estimated_pomodoros: 3,
      completed_pomodoros: 0,
      due_date: null,
      completed_at: null,
      notes: '- [ ] Tạo link subscription .ics bảo mật cho từng user\n- [ ] Hỗ trợ xác thực OAuth Google Calendar\n- [ ] Thay đổi ngày trên Google Calendar tự động cập nhật task',
    },

    // --- EPIC 3: Multi-Agent Parallel Orchestration & Swarm (P0) ---
    {
      id: 109,
      project_id: 1,
      issue_key: 'THUB-09',
      title: 'Isolated Git Worktree Parallel Runner (Chạy song song Agent trên Git Worktree)',
      description: 'Cơ chế tự động tạo thư mục Git Worktree và nhánh riêng cho mỗi tác tử AI, cho phép lập trình viên chạy song song 3 task khác nhau cùng lúc trên cùng một repository.',
      status: 'in_progress',
      priority: 'urgent',
      category: 'ai',
      estimated_pomodoros: 4,
      completed_pomodoros: 2,
      due_date: todayStr,
      completed_at: null,
      notes: '- [x] Tạo nhánh git riêng dạng `feat/THUB-XX` trên worktree cô lập\n- [x] Độc lập biến môi trường và tiến trình biên dịch\n- [ ] Tự động gỡ bỏ worktree an toàn sau khi merge hoặc hủy',
    },
    {
      id: 110,
      project_id: 1,
      issue_key: 'THUB-10',
      title: 'Agent Roles Pipeline: Spec → Code → Test (Kịch bản phân vai tác tử)',
      description: 'Quy trình cộng tác 3 vai trò tự động: Architect Agent phân tích issue và sinh tài liệu đặc tả -> Coder Agent lập trình mã nguồn -> QA Agent chạy test tự động.',
      status: 'todo',
      priority: 'urgent',
      category: 'ai',
      estimated_pomodoros: 4,
      completed_pomodoros: 0,
      due_date: tomorrowStr,
      completed_at: null,
      notes: '- [ ] Chuyển giao ngữ cảnh (context artifacts) tự động giữa các bước\n- [ ] Có nút phê duyệt (Approval Gate) giữa giai đoạn Spec và Code\n- [ ] Hiển thị tiến trình trực quan trên FlowStepper stepper 4 giai đoạn',
    },
    {
      id: 111,
      project_id: 1,
      issue_key: 'THUB-11',
      title: 'Extended Agent CLI Runners: Codex, Cursor, Copilot (Mở rộng bộ chạy Agent CLI)',
      description: 'Bổ sung trình kết nối và stream output chuẩn hóa cho OpenAI Codex CLI, Cursor Agent CLI và GitHub Copilot Workspace CLI ngoài Antigravity và Claude Code.',
      status: 'todo',
      priority: 'medium',
      category: 'ai',
      estimated_pomodoros: 3,
      completed_pomodoros: 0,
      due_date: nextWeekStr,
      completed_at: null,
      notes: '- [ ] Tự động phát hiện CLI đã cài trong hệ điều hành\n- [ ] Chuẩn hóa telemetry tokens và output stream về chung 1 format\n- [ ] Cho phép chuyển đổi nhanh provider trên giao diện',
    },
    {
      id: 112,
      project_id: 1,
      issue_key: 'THUB-12',
      title: 'Auto-Healing Loop & Interactive Terminal Takeover (Tự gỡ kẹt vòng lặp & Can thiệp tay)',
      description: 'Thuật toán chẩn đoán phát hiện khi Agent bị kẹt trong vòng lặp sửa lỗi lặp đi lặp lại (> 3 lần cùng 1 lỗi biên dịch) để tự động dừng và mở terminal PTY tương tác cho kỹ sư.',
      status: 'todo',
      priority: 'medium',
      category: 'ai',
      estimated_pomodoros: 3,
      completed_pomodoros: 0,
      due_date: nextWeekStr,
      completed_at: null,
      notes: '- [ ] Nhận diện mẫu lặp log lặp lại chính xác trong vòng 3 chu kỳ\n- [ ] Tạm dừng an toàn tiến trình agent mà không mất ngữ cảnh\n- [ ] Cho phép dev gõ lệnh trực tiếp trong terminal nhúng',
    },

    // --- EPIC 4: Evidence-Driven QA & Git Automation (P1) ---
    {
      id: 113,
      project_id: 1,
      issue_key: 'THUB-13',
      title: 'Automated Pull Request & Conventional Commits (Tự động commit & Mở GitHub PR)',
      description: 'Sau khi Agent hoàn thành công việc và vượt qua kiểm thử, hệ thống tự động gom commit theo chuẩn Conventional Commits (feat, fix), đẩy lên remote và tạo PR kèm bằng chứng.',
      status: 'todo',
      priority: 'urgent',
      category: 'ai',
      estimated_pomodoros: 3,
      completed_pomodoros: 0,
      due_date: todayStr,
      completed_at: null,
      notes: '- [ ] Sinh commit message chuẩn xác dựa trên git diff\n- [ ] Mở PR trên GitHub API kèm Markdown bằng chứng (Test Pass Rate, Diff)\n- [ ] Đính kèm liên kết ngược về Task Hub Issue',
    },
    {
      id: 114,
      project_id: 1,
      issue_key: 'THUB-14',
      title: 'Visual Acceptance Criteria Auto-Verifier (Tự động kiểm chứng tiêu chí nghiệm thu)',
      description: 'Trình phân tích đối chiếu từng dòng tiêu chí Acceptance Criteria dạng checklist - [ ] và chạy lệnh test tương ứng để tự động tích xanh - [x] khi code đáp ứng yêu cầu.',
      status: 'todo',
      priority: 'high',
      category: 'ai',
      estimated_pomodoros: 3,
      completed_pomodoros: 0,
      due_date: tomorrowStr,
      completed_at: null,
      notes: '- [ ] Bóc tách danh sách AC từ mô tả công việc\n- [ ] Chạy lệnh kiểm thử xác nhận từng tiêu chí\n- [ ] Đánh dấu hoàn thành tự động trên giao diện kèm bằng chứng log',
    },
    {
      id: 115,
      project_id: 1,
      issue_key: 'THUB-15',
      title: 'Local Semantic Vector Codebase Search / RAG (Tìm kiếm ngữ nghĩa mã nguồn cục bộ)',
      description: 'Trình đánh chỉ mục vector mã nguồn cục bộ, cho phép Agent tra cứu nhanh các hàm, component và luồng xử lý liên quan trong dự án lớn trong < 200ms.',
      status: 'todo',
      priority: 'medium',
      category: 'ai',
      estimated_pomodoros: 4,
      completed_pomodoros: 0,
      due_date: nextWeekStr,
      completed_at: null,
      notes: '- [ ] Đánh chỉ mục cục bộ không gửi code ra bên ngoài\n- [ ] Tìm kiếm ngữ nghĩa trả về top đoạn code liên quan nhất\n- [ ] Cập nhật chỉ mục gia tăng khi file thay đổi',
    },
    {
      id: 116,
      project_id: 1,
      issue_key: 'THUB-16',
      title: 'Docker Sandbox Safe Runner (Môi trường thực thi cô lập an toàn)',
      description: 'Chạy toàn bộ lệnh terminal và mã nguồn do AI Agent sinh ra bên trong Docker container cô lập, bảo vệ máy tính của lập trình viên khỏi các lệnh nguy hiểm.',
      status: 'todo',
      priority: 'low',
      category: 'ai',
      estimated_pomodoros: 3,
      completed_pomodoros: 0,
      due_date: null,
      completed_at: null,
      notes: '- [ ] Khởi chạy nhanh container dựa trên cấu hình Dockerfile của dự án\n- [ ] Giới hạn CPU/RAM và chặn truy cập thư mục ngoài workspace\n- [ ] Xóa sạch container sau khi phiên chạy kết thúc',
    },

    // --- EPIC 5: Agile Workspaces, Kanban & Real-time Collaboration (P0) ---
    {
      id: 117,
      project_id: 1,
      issue_key: 'THUB-17',
      title: 'Interactive Drag-and-Drop Kanban Board (Bảng Kanban kéo thả trực quan)',
      description: 'Giao diện bảng Kanban thời gian thực với các cột Backlog, To Do, In Progress, Review, Done; hỗ trợ kéo thả thẻ mượt mà, phân loại thẻ theo màu sắc dự án và bộ lọc đa chiều.',
      status: 'in_progress',
      priority: 'urgent',
      category: 'cloud',
      estimated_pomodoros: 3,
      completed_pomodoros: 1,
      due_date: todayStr,
      completed_at: null,
      notes: '- [x] Khởi tạo giao diện các cột Kanban chuẩn Agile\n- [ ] Kéo thả thẻ mượt mà giữa các cột với animation tự nhiên\n- [ ] Tự động cập nhật status của task trong database\n- [ ] Bộ lọc tức thời theo Sprint, Priority, Assignee và Tags',
    },
    {
      id: 118,
      project_id: 1,
      issue_key: 'THUB-18',
      title: 'Real-time Multi-User Sync via Laravel Reverb (Đồng bộ đa người dùng thời gian thực)',
      description: 'Tích hợp Laravel Reverb WebSockets để phản ánh tức thì mọi thay đổi về công việc, trạng thái, bình luận và hiển thị avatar của các thành viên đang cùng xem hoặc sửa một task.',
      status: 'todo',
      priority: 'urgent',
      category: 'cloud',
      estimated_pomodoros: 4,
      completed_pomodoros: 0,
      due_date: tomorrowStr,
      completed_at: null,
      notes: '- [ ] Độ trễ phát tán sự kiện < 150ms tới toàn bộ client đang mở\n- [ ] Hiển thị avatar presence của những ai đang xem cùng 1 task\n- [ ] Chống ghi đè xung đột (optimistic locking alert)',
    },
    {
      id: 119,
      project_id: 1,
      issue_key: 'THUB-19',
      title: 'Multi-tenant Workspaces & Role-Based Access Control (Không gian làm việc & Phân quyền RBAC)',
      description: 'Hệ thống cho phép người dùng tham gia nhiều Workspace (công ty, nhóm nghiên cứu, dự án cá nhân). Hỗ trợ phân quyền chặt chẽ các vai trò: Owner, Admin, Member, Client / Viewer.',
      status: 'todo',
      priority: 'high',
      category: 'cloud',
      estimated_pomodoros: 3,
      completed_pomodoros: 0,
      due_date: nextWeekStr,
      completed_at: null,
      notes: '- [ ] Chuyển đổi nhanh giữa các Workspace trên thanh điều hướng\n- [ ] Phân quyền xem và sửa dự án/task theo vai trò\n- [ ] Bảo đảm cô lập dữ liệu tuyệt đối giữa các Workspace',
    },
    {
      id: 120,
      project_id: 1,
      issue_key: 'THUB-20',
      title: 'Activity Stream, Markdown Comments & @Mentions (Nhật ký hoạt động & Bình luận @)',
      description: 'Khung thảo luận cho từng công việc hỗ trợ cú pháp Markdown phong phú, dán ảnh chụp màn hình, gắn thẻ tên đồng đội @username kèm theo dòng nhật ký ghi lại toàn bộ lịch sử chỉnh sửa.',
      status: 'todo',
      priority: 'medium',
      category: 'cloud',
      estimated_pomodoros: 2,
      completed_pomodoros: 0,
      due_date: tomorrowStr,
      completed_at: null,
      notes: '- [ ] Trình soạn thảo bình luận hỗ trợ Markdown và dán ảnh clipboard\n- [ ] Gõ @ hiển thị danh sách gợi ý thành viên trong Workspace\n- [ ] Gửi thông báo trong app và email cho người được nhắc tên',
    },

    // --- EPIC 6: Ecosystem, Templates & Omnichannel Notifications (P1) ---
    {
      id: 121,
      project_id: 1,
      issue_key: 'THUB-21',
      title: 'Omnichannel Webhook & Notification Hub (Trung tâm thông báo đa kênh Slack, Telegram, Discord, Zalo)',
      description: 'Hệ thống điều phối thông báo đa kênh: tự động gửi tin nhắn dạng Card đẹp mắt về kênh Slack, Discord, bot Telegram hoặc Zalo khi có task mới được giao, task trễ hạn.',
      status: 'todo',
      priority: 'urgent',
      category: 'cloud',
      estimated_pomodoros: 3,
      completed_pomodoros: 0,
      due_date: todayStr,
      completed_at: null,
      notes: '- [ ] Cấu hình webhook linh hoạt cho từng kênh\n- [ ] Gửi thẻ tin nhắn phong phú với các nút bấm Approve / View Task\n- [ ] Cho phép lọc loại sự kiện muốn nhận thông báo',
    },
    {
      id: 122,
      project_id: 1,
      issue_key: 'THUB-22',
      title: 'Project Workflow Template Marketplace (Chợ mẫu quy trình dự án khởi tạo 1-click)',
      description: 'Thư viện các quy trình dự án được chuẩn hóa sẵn (Scrum Software Sprint, Content Marketing Campaign, Tuyển dụng nhân sự, Fullstack AI Workflow) cho phép tạo ngay dự án hoàn chỉnh.',
      status: 'todo',
      priority: 'medium',
      category: 'cloud',
      estimated_pomodoros: 3,
      completed_pomodoros: 0,
      due_date: nextWeekStr,
      completed_at: null,
      notes: '- [ ] Xem trước cấu trúc task và milestone trước khi kích hoạt\n- [ ] Tạo dự án mới kèm đầy đủ task và checklist chỉ bằng 1 click\n- [ ] Cho phép người dùng lưu dự án hiện tại thành template riêng',
    },
    {
      id: 123,
      project_id: 1,
      issue_key: 'THUB-23',
      title: 'Public Roadmap & Customer Feature Voting Portal (Cổng bình chọn tính năng công khai)',
      description: 'Trang Roadmap công khai cho phép khách hàng và người dùng cuối xem kế hoạch phát triển, đóng góp ý kiến và bình chọn tính năng.',
      status: 'todo',
      priority: 'medium',
      category: 'cloud',
      estimated_pomodoros: 3,
      completed_pomodoros: 0,
      due_date: nextWeekStr,
      completed_at: null,
      notes: '- [ ] Trang công khai có giao diện hiện đại với danh sách tính năng theo cột\n- [ ] Người dùng có thể bấm Upvote và để lại bình luận góp ý\n- [ ] Tự động đồng bộ số vote và chuyển trạng thái sang In Backlog',
    },
    {
      id: 124,
      project_id: 1,
      issue_key: 'THUB-24',
      title: 'Cloud MCP Gateway & Tool Registry Sync (Đồng bộ danh mục công cụ MCP trên Cloud)',
      description: 'Cổng quản lý và đồng bộ danh mục công cụ Model Context Protocol (MCP) trên Cloud. Giúp các kỹ sư cấu hình công cụ MCP 1 lần trên Web và tự động đồng bộ xuống tất cả máy tính.',
      status: 'todo',
      priority: 'low',
      category: 'cloud',
      estimated_pomodoros: 3,
      completed_pomodoros: 0,
      due_date: null,
      completed_at: null,
      notes: '- [ ] Quản lý danh sách MCP Server và API keys bảo mật trên Cloud\n- [ ] Desktop Companion tự động tải cấu hình MCP khi đăng nhập\n- [ ] Kiểm tra ping trạng thái hoạt động của từng công cụ MCP',
    },
  ];
}
